print("Hello World")
n1=int(input("Enter a number"))
n2=int(input("Enter another number"))
print("Sum: ", n1+n2)
print("Difference: ", n1-n2)
print("Product: ", n1*n2)
print("Int Division: ", n1//n2)
print("Float Division: ", n1/n2)
print("Floor Division: ", n1%n2)
print("Modulo: ", n1%n2)